'use client';
import {useEffect,useMemo,useState} from 'react';import {BeforeAfter} from './BeforeAfter';import type {ArchitectureLocks,RoomType,StageMode,StageResult,StageStyle} from '../lib/staging/types';
const STYLES:[StageStyle,string][]=[['modern','Moderno'],['minimal','Minimal'],['mediterranean','Mediterraneo'],['scandinavian','Scandinavo'],['luxury','Luxury'],['industrial','Industrial'],['japandi','Japandi'],['rustic-chic','Rustico Chic']];
const LOCKS:Record<keyof ArchitectureLocks,string>={walls:'Muri e geometria',floor:'Pavimenti',windowsDoors:'Porte e finestre',fixtures:'Infissi e impianti fissi',kitchen:'Cucina fissa',sanitary:'Sanitari'};
type Provider={name:string;mode:'live'|'demo';ready:boolean};type Hist={id:string;at:string;style:string;room:string;provider:string;variants:number;elapsedMs:number};
export function Studio(){const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState('');const[room,setRoom]=useState<RoomType>('auto');const[mode,setMode]=useState<StageMode>('declutter-stage');const[style,setStyle]=useState<StageStyle>('modern');const[count,setCount]=useState(4);const[locks,setLocks]=useState<ArchitectureLocks>({walls:true,floor:true,windowsDoors:true,fixtures:true,kitchen:true,sanitary:true});const[result,setResult]=useState<StageResult|null>(null);const[selected,setSelected]=useState(0);const[busy,setBusy]=useState(false);const[msg,setMsg]=useState('');const[provider,setProvider]=useState<Provider>({name:'Verifica…',mode:'demo',ready:false});const[tab,setTab]=useState<'studio'|'history'|'provider'>('studio');const[history,setHistory]=useState<Hist[]>([]);
useEffect(()=>{fetch('/api/provider').then(r=>r.json()).then(setProvider).catch(()=>{});try{setHistory(JSON.parse(localStorage.getItem('estate-stage-history')||'[]'))}catch{}},[]);const canGenerate=useMemo(()=>!!file&&!busy&&Object.values(locks).filter(Boolean).length>=3,[file,busy,locks]);const variant=result?.variants[selected];
function choose(f:File|null){if(preview)URL.revokeObjectURL(preview);setFile(f);setPreview(f?URL.createObjectURL(f):'');setResult(null);setSelected(0);setMsg('')}
function remember(r:StageResult){const item:Hist={id:r.jobId,at:new Date().toISOString(),style,room,provider:r.provider,variants:r.variants.length,elapsedMs:r.elapsedMs};const next=[item,...history].slice(0,30);setHistory(next);localStorage.setItem('estate-stage-history',JSON.stringify(next))}
async function generate(){if(!file)return;setBusy(true);setResult(null);setMsg('Input Validator → Prompt Architect → Architecture Guardian…');try{const fd=new FormData();fd.append('image',file);fd.append('payload',JSON.stringify({roomType:room,mode,style,locks,variants:count}));const res=await fetch('/api/stage',{method:'POST',body:fd});const data=await res.json();if(!res.ok)throw new Error(data.error||'Generazione fallita');setResult(data);setSelected(0);setMsg(data.message);remember(data)}catch(e){setMsg(e instanceof Error?e.message:'Errore inatteso')}finally{setBusy(false)}}
function download(){if(!variant)return;const a=document.createElement('a');a.href=variant.imageUrl;a.target='_blank';a.download=`estate-stage-${style}-${selected+1}.jpg`;a.click()}
return <div className="app"><aside><div className="brand">EstateStage <b>AI</b></div><button onClick={()=>setTab('studio')} className={tab==='studio'?'active':''}>Studio</button><button onClick={()=>setTab('history')} className={tab==='history'?'active':''}>Cronologia <span>{history.length}</span></button><button onClick={()=>setTab('provider')} className={tab==='provider'?'active':''}>Provider</button><div className="side-note"><strong>Architecture Lock</strong><p>Lo staging deve rispettare l’immobile reale. Verifica umana obbligatoria prima della pubblicazione.</p></div><small>MVP v0.3</small></aside><main><header><div><p>VIRTUAL STAGING WORKSPACE</p><h1>{tab==='studio'?'Trasforma una stanza senza alterare l’immobile.':tab==='history'?'Cronologia delle generazioni.':'Stato del motore AI.'}</h1></div><span className={`provider ${provider.ready?'live':''}`}>{provider.ready?'LIVE':'DEMO'} · {provider.name}</span></header>
{tab==='history'&&<section className="panel wide"><div className="row"><div><h2>Generazioni recenti</h2><p>Metadati conservati nel browser.</p></div><button className="secondary" onClick={()=>{setHistory([]);localStorage.removeItem('estate-stage-history')}}>Svuota</button></div>{!history.length?<div className="empty">Nessuna generazione.</div>:history.map(x=><div className="hist" key={x.id}><div><b>{x.style} · {x.room}</b><small>{new Date(x.at).toLocaleString('it-IT')}</small></div><span>{x.provider}</span><span>{x.variants} varianti</span><span>{(x.elapsedMs/1000).toFixed(1)} s</span></div>)}</section>}
{tab==='provider'&&<section className="providers"><div className="panel"><p>PROVIDER ATTIVO</p><h2>{provider.name}</h2><b className={provider.ready?'green':'amber'}>{provider.ready?'Pronto':'Demo'}</b><p>{provider.ready?'Generazione AI attiva server-side.':'Configura FAL_KEY su Vercel per attivare FLUX Kontext.'}</p></div><div className="panel"><p>SICUREZZA</p><h2>Server-side only</h2><p>La chiave non raggiunge mai il browser. Input ammessi: JPG, PNG, WEBP, max 10 MB.</p></div><div className="panel"><p>QUALITY GATE</p><h2>Human review</h2><p>Nessun punteggio strutturale viene inventato: l'output resta da verificare prima della pubblicazione.</p></div></section>}
{tab==='studio'&&<section className="grid"><div className="panel controls"><h2>01 · Fotografia</h2><label className="upload"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>choose(e.target.files?.[0]||null)}/>{preview?<img src={preview} alt="Input"/>:<span>＋<b>Carica fotografia</b><small>JPG, PNG o WEBP · max 10 MB</small></span>}</label><h2>02 · Configurazione</h2><label>Ambiente</label><select value={room} onChange={e=>setRoom(e.target.value as RoomType)}><option value="auto">Riconoscimento automatico</option><option value="living">Soggiorno</option><option value="bedroom">Camera</option><option value="kitchen">Cucina</option><option value="bathroom">Bagno</option><option value="office">Ufficio</option><option value="dining">Sala da pranzo</option><option value="outdoor">Esterno</option></select><div className="seg"><button className={mode==='restyle'?'active':''} onClick={()=>setMode('restyle')}>Restyle</button><button className={mode==='declutter-stage'?'active':''} onClick={()=>setMode('declutter-stage')}>Svuota + Staging</button></div><label>Stile</label><div className="styles">{STYLES.map(([id,name])=><button key={id} className={style===id?'active':''} onClick={()=>setStyle(id)}>{name}</button>)}</div><label>Varianti</label><div className="seg four">{[1,2,3,4].map(n=><button key={n} className={count===n?'active':''} onClick={()=>setCount(n)}>{n}</button>)}</div></div>
<div className="panel preview"><div className="preview-head"><div><p>ANTEPRIMA</p><h2>Prima / Dopo</h2></div><span>Virtual staging AI</span></div>{!preview?<div className="empty">Carica una fotografia per iniziare.</div>:variant?<BeforeAfter before={preview} after={variant.imageUrl}/>:<div className="single"><img src={preview} alt="Originale"/><b>ORIGINALE</b></div>}{result&&<><div className="variants">{result.variants.map((v,i)=><button key={v.id} className={i===selected?'active':''} onClick={()=>setSelected(i)}><img src={v.imageUrl} alt={v.label}/><small>{v.label}</small></button>)}</div><div className="resultbar"><span>{result.provider}</span><span>{(result.elapsedMs/1000).toFixed(1)} s</span><span>Review richiesta</span><button onClick={download}>Scarica</button></div></>}</div>
<div className="panel locks"><h2>03 · Architecture Lock</h2><p>Elementi da preservare.</p>{(Object.keys(locks) as (keyof ArchitectureLocks)[]).map(k=><label className="lock" key={k}><span>{LOCKS[k]}</span><input type="checkbox" checked={locks[k]} onChange={()=>setLocks({...locks,[k]:!locks[k]})}/></label>)}<div className="policy"><b>Policy immobiliare</b><p>Solo arredi e decorazione. Vietati cambi di geometria, aperture, pavimenti, prospettiva e impianti fissi selezionati.</p></div><button className="generate" disabled={!canGenerate} onClick={generate}>{busy?'Generazione in corso…':provider.ready?'Genera staging AI':'Esegui pipeline demo'}</button>{msg&&<div className="message">{msg}</div>}{result&&<details><summary>Pipeline tecnica</summary><ol>{result.pipeline.map(x=><li key={x}>{x}</li>)}</ol></details>}<small className="legal">Prima della pubblicazione confrontare sempre l'output con la fotografia originale e indicare “Virtual Staging AI”.</small></div></section>}</main></div>}
